### ISSUE TITLE
Chrome导入插件报错 

### ISSUE THREAD

**Issue by SuchaharCan** [Kenshin/emoji#8]
现在检测 头文件,发现不是官方商店的,就不允许安装,这个怎么解决呢?

**Comment by Kenshin** [comment]
使用 [Edge 版](https://microsoftedge.microsoft.com/addons/detail/%E7%AE%80%E6%82%A6-simpread/clgdhlhfiocphghdkdbgdlmfaafccfmc?hl=zh-CN) 或者 [离线版](http://ksria.com/simpread/wiki/#/Download)
